[package]
name = "correlation_with_nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tqdm-rs = "0.1.1"

[dependencies.ising_lib]
path = "../../"
